name: artifact-upload

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    if: github.ref_type == 'tag'
    name: Artifact creation
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        id: checkout
        run: echo "VERSION=$(type .\VERSION.txt)" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v6
        with:
          node-version: '22.11'
      - uses: actions/setup-python@v6
        with:
          python-version: '>=3.11 <3.14'
      - name: Python setup
        run: pip install -r requirements.txt
      - name: Artifact build
        run: |
          echo "Current directory: $(pwd)"
          .\build.ps1
      - name: ZIP packaging
        id: package
        run: |
          compress-archive .\entrabulker\ ".\entrabulker-${{ steps.checkout.outputs.VERSION }}.zip" -compressionlevel fastest
      - name: File confirmation
        run: |
          if(!(test-path ".\entrabulker-${{ steps.checkout.outputs.VERSION }}.zip")){
            echo "Failed to create ZIP file"
            exit 1
          }
      - name: Artifact upload
        uses: softprops/action-gh-release@v2
        with:
          files: "./entrabulker-${{ steps.checkout.outputs.VERSION }}.zip"